baseURL = 'https://wxzhang818.github.io'
languageCode = 'en-us'
title = 'wenwen'
theme = "terminal"
canonifyURLs = true

[menus]
  [[menus.main]]
    identifier = "about"
    name = "About"
    url = "/about.html"
    weight = 20
  [[menus.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 30
  [[menus.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 40

[params]
  disqus = "" # Optional: Add your Disqus shortname
  [[params.social]]
    name = "github"
    url = "https://github.com/wxzhang818"
